#!/bin/bash
#$ cat > menuui
#
# Script to create simple menus and take action according to that selected
# menu item
# function egs
#
function getRepo(){
tempfile="$(mktemp)"
while true; do
    dialog --menu 'Please select from the server list--Do twice' 18 70 15 $(nl server.list) 2>"$tempfile" && break
done
n="$(cat "$tempfile")"
Repo="$(sed -n "${n}p" server.list)"
rm "$tempfile"
#echo "The user selected option number $n: '$value'"
clear
#echo $Repo
return
}
function getStatus(){
   cd $Repo
   echo "Status for $Repo"
   git status 
   return
}
function gitPull(){
   cd $Repo
   git pull origin main
   return
}
function gitAdd(){
   cd $Repo
   git add .
   return
}
function gitCommit(){
   cd $Repo
   git commit -m "Lenovo update"
   return
}
function gitPush(){
   cd $Repo
   git push origin main
   return
}
while :
 do
    clear
    echo "-------------------------------------"
    echo " Main Menu "
    echo "-------------------------------------"
    echo "[1] Get Repo value"
    echo "[2] Get Status"
    echo "[3] gitPull"
    echo "[4] gitAdd"
    echo "[5] gitCommit"
    echo "[6] gitPush"
    echo "[9] Exit/Stop"
    echo "======================="
    echo -n "Enter your menu choice [1-8]: "
    read yourch
    case $yourch in
      1) getRepo;getRepo ; read ;;
      2) getStatus;getStatus; read ;;
      3) gitPull;gitPull; read ;;
      4) gitAdd;gitAdd; read ;;
      5) gitCommit;gitCommit; read ;;
      6) gitPush;gitPush; read ;;
      9) exit 0 ;;
      *) echo "Opps!!! Please select choice 1,2,3,4,5,6, or 9";
         echo "Press a key. . ." ; read ;;
 esac
done
