#!/bin/bash
# Bash Menu Script Example
# https://unix.stackexchange.com/questions/574039/how-do-i-write-a-bash-menu-script-so-that-the-options-are-the-contents-of-a-list
# https://stackoverflow.com/questions/51616985/how-to-display-a-selection-menu-in-bash-using-options-that-are-stored-in-a-text
# read menu file line-by-line, save as $line
unset option menu ERROR      # prevent inheriting values from the shell
declare -a menu              # create an array called $menu
menu[0]=""                   # set and ignore index zero so we can count from 1

while IFS= read -r line; do
  menu[${#menu[@]}]="$line"  # push $line onto $menu[]
done < ~/Repositories/home-bin/repo.list

# function to show the menu
menu() {
  echo "Please select an option by typing in the corresponding number"
  echo ""
  for (( i=1; i<${#menu[@]}; i++ )); do
    echo "$i) ${menu[$i]}"
  done
  echo ""
}

# initial menu
menu
read option

# loop until given a number with an associated menu item
while ! [ "$option" -gt 0 ] 2>/dev/null || [ -z "${menu[$option]}" ]; do
  echo "No such option '$option'" >&2  # output this to standard error
  menu
  read option
done
#Repo=${menu[$option]}
#echo "${Repo}"
#echo "You said '$option' which is '${menu[$option]}'"
#echo "You chosen '${menu[$option]}'"
Repo=${menu[$option]}
#Repo=${menu[$option]}
echo "You have chosen" "$Repo"
return
