#!/bin/bash


# Licence: GNU GPL v3
# Version: 1
# Script use:   bash script_name
# This is example script

# Function in yad is not supported but it can work after 
# add in script "export -f function_name" 
# and will work as a separate process like command.


yad --title="TITLE"\
      --form \
      --no-escape \
      --center \
      --window-icon=gtk-preferences \
      --borders=10 \
      --fixed  \
      --text="TEST" --text-align=center \
      --button="LIST"!format-justify-fill:0  \
      --button="gtk-cancel":1 
VAR1="$?"
echo "  DEBUG: VAR1 = $VAR1" 


FUNCTION_VAR2 () {
INPUT=$(echo -e "one \naple \ntwo\nbanana \ntree \ncitrine \nfour \nnewfruit")

VAR2=$( echo "$INPUT" | yad --title="TITLE 2" \
--text="Select the correct one row:" \
--borders=10 \
--listen \
--no-markup \
--width=500 \
--height=500 \
--no-escape \
--center \
--window-icon=gtk-preferences \
--list \
--column="COLUMN 1":text \
--column="COLUMN 2":text \
--button="OK"!go-jump:0 \
--button="gtk-cancel":1 )

echo "  DEBUG: VAR2 = $VAR2" 
VAR3=$(echo "$VAR2" | awk -F"|" '{ print $1 }')
VAR4=$(echo "$VAR2" | awk -F"|" '{ print $2 }')
echo "  DEBUG: VAR3 = $VAR3" 
echo "  DEBUG: VAR4 = $VAR4" 
}


[[ "$VAR1" == "0" ]] && FUNCTION_VAR2

echo $FUNCTION_VAR2