#!/bin/bash
#dialog --no-cancel --menu "Please select from the list below or enter the build number you would like to download " 11 60 12 1 Latest 2 Successful 3 Stable
dialog  --menu "Please select from the list below or enter the build number you would like to download " 11 60 12 1 Latest 2 Successful 3 Stable

echo '$Repo'
# https://unix.stackexchange.com/questions/566953/parsing-variable-which-contains-vertical-bar
# https://stackoverflow.com/questions/28420705/bash-script-to-let-user-choose-from-a-list-or-enter-their-own